// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// NPtest_indept
List NPtest_indept(DataFrame dat, int k);
RcppExport SEXP _fastPSSIM_NPtest_indept(SEXP datSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(NPtest_indept(dat, k));
    return rcpp_result_gen;
END_RCPP
}
// makepseudo
List makepseudo(int N, IntegerVector n, int k, int a, NumericMatrix alltrt);
RcppExport SEXP _fastPSSIM_makepseudo(SEXP NSEXP, SEXP nSEXP, SEXP kSEXP, SEXP aSEXP, SEXP alltrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alltrt(alltrtSEXP);
    rcpp_result_gen = Rcpp::wrap(makepseudo(N, n, k, a, alltrt));
    return rcpp_result_gen;
END_RCPP
}
// mapindex
IntegerVector mapindex(int r, IntegerVector n);
RcppExport SEXP _fastPSSIM_mapindex(SEXP rSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mapindex(r, n));
    return rcpp_result_gen;
END_RCPP
}
// trt_position
IntegerVector trt_position(int i1, IntegerVector n);
RcppExport SEXP _fastPSSIM_trt_position(SEXP i1SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(trt_position(i1, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastPSSIM_NPtest_indept", (DL_FUNC) &_fastPSSIM_NPtest_indept, 2},
    {"_fastPSSIM_makepseudo", (DL_FUNC) &_fastPSSIM_makepseudo, 5},
    {"_fastPSSIM_mapindex", (DL_FUNC) &_fastPSSIM_mapindex, 2},
    {"_fastPSSIM_trt_position", (DL_FUNC) &_fastPSSIM_trt_position, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastPSSIM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
