# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test of independence in the presence of heteroscedastic treatments
#' 
#' @description
#' \code{NPtest_indept()} performs the test of independence between the 
#' response variable and a single covariate when there is potentially 
#' heteroscedastic treatment effects present (see Wang, Tolos and Wang (2010)).
#' 
#' This is a rewrite of the original \code{NPtest_indept()} function from the
#' PSSIM library using Rcpp to decrease runtime. If you load both this library 
#' and PSSIM, load this one second so the faster functions will overwrite the 
#' slower ones.
#'
#' @param dat A dataframe with three columns named X, trt, and Y, where X is
#' the covariate, trt is the treatment level, and Y is the response variable.
#' @param k An odd integer to specify the number of nearest neighbors to be
#' used in augmentation. Generally recommend to use 3, 5, or 7.
#' 
#' @return A list containing the following variables:
#' \itemize{
#'   \item \strong{Asys_var}: The asymptotic variance for the test statistics.
#'   \item \strong{Tstat}: The test statistic.
#'   \item \strong{pvalue}: The p-value of the test under \eqn{H_0}:
#'   There is independence between X and Y.
#' }
#' 
#' @examples
#' n = 64;  X = runif(n); trt = gl(2, n/2)
#' e = rnorm(n, 0, 0.1)
#' Y = ifelse(trt == 1, 4*(X-0.5)^2+e, 2*X+e)
#' dat = data.frame(X, Y, trt)
#' NPtest_indept(dat, k = 7)
#'  
#' @seealso \code{\link[=makepseudo]{makepseudo}}, 
#' \code{\link[=mapindex]{mapindex}}, and  
#' \code{\link[=trt_position]{trt_position}} are all called within this.
#' 
#' @references
#' Haiyan Wang, Siti Tolos, and Suojin Wang (2010). A Distribution Free
#'  Nonparametric Test to Detect Dependence Between a Response Variable and
#'  Covariate in Presence of Heteroscedastic Treatment Effects.
#'  The Canadian Journal of Statistics. 38(3), 408433. Doi:10.1002/cjs.10068
#' 
#' @useDynLib fastPSSIM
#' 
#' @export
NPtest_indept <- function(dat, k = 7L) {
    .Call(`_fastPSSIM_NPtest_indept`, dat, k)
}

#' Nearest neighbor augmentation based on ranks
#' 
#' @description
#' The function \code{makepseudo()} performs the nearest neighbor augmentation 
#' based on the rank of covariate values according to the scheme described on 
#' page 410-411 of Wang, Tolos and Wang (2010). 
#' 
#' This is a rewrite of the original \code{makepseudo()} function from the 
#' PSSIM library using Rcpp to decrease runtime. If you load both this library 
#' and PSSIM, load this one second so the faster functions will overwrite the 
#' slower ones.
#'
#' @param N Total number of covariate values.
#' @param n Vector of sample sizes from all treatments.
#' @param k Number of nearest neighbors.
#' @param a Number of treatment levels in the data.
#' @param alltrt A matrix of dimension 3x\code{N}, with first two rows being Y 
#'   and X, and a third row with the rank of the X values within the same 
#'   treatment level. 
#' 
#' @return A list containing the following:
#' \itemize{
#'   \item \strong{psudo}: A 3D array of dimensions (\code{k}, \code{a}, 
#'   \code{N}) that stores the augmented observations based on the k-nearest 
#'   neighbor rule in Wang, Tolos and Wang (2010).
#'   \item \strong{index}: A 3D array of dimensions (\code{k}, \code{a}, 
#'   \code{N}) that stores the indices of the observations used for 
#'   augmentation.
#' }
#' 
#' @examples
#'  a = 2; n = c(7, 9); N = sum(n);  X = runif(N);
#'  trt = c(rep(1, n[1]), rep(2, n[2])); e = rnorm(N, 0, 0.1)
#'  Y = ifelse(trt == 1, 4*(X-0.5)^2+e, 2*X+e)
#'  ranksuse = unlist(tapply(X, trt, rank))
#'  alltrt = rbind(Y, X, ranksuse)
#'  aug = makepseudo(N, n, k=3, a, alltrt)
#'  
#' @seealso \code{\link[=NPtest_indept]{NPtest_indept}} uses this function to 
#' run the independence test.
#' 
#' @references
#' Haiyan Wang, Siti Tolos, and Suojin Wang (2010). A Distribution Free
#'  Nonparametric Test to Detect Dependence Between a Response Variable and
#'  Covariate in Presence of Heteroscedastic Treatment Effects.
#'  The Canadian Journal of Statistics. 38(3), 408433. Doi:10.1002/cjs.10068
#' 
#' @useDynLib fastPSSIM
#' 
#' @export
makepseudo <- function(N, n, k, a, alltrt) {
    .Call(`_fastPSSIM_makepseudo`, N, n, k, a, alltrt)
}

#' Index in one vector mapped to treatment and observation index
#' 
#' @description
#' Function \code{mapindex()} maps the 1-d index \eqn{r = 1, \ldots, N} to 2-d 
#' index \eqn{i = 1, \ldots, a}, \eqn{j = 1, \ldots, n_i}{j = 1, ..., n_i}. 
#' Generally the covariate values from all treatments are stored together in 
#' one vector and \eqn{r = 1, \ldots, N} enumerates the values. For any integer
#' between 1 and \eqn{N}, \code{mapindex()} tells which treatment the 
#' \eqn{r^{th}} value belongs to, and which observation in the identified 
#' treatment.
#' 
#' This is a rewrite of the original \code{mapindex()}function from the PSSIM
#' library using Rcpp to decrease runtime. If you load both this library and 
#' PSSIM, load this one second so the faster functions will overwrite the 
#' slower ones.
#'
#' @param r An integer between 1 and \code{num(n)}.
#' @param n A vector of the sample sizes.
#' 
#' @return A 2-d index, where the first gives which treatment \code{r} belongs 
#' to and the second gives which observation \code{r} is within that treatment.
#' 
#' @examples
#' r = 5; n = c(7, 8); mapindex(r, n)
#' r = 7; n = c(7, 8); mapindex(r, n)
#' r = 9; n = c(7, 8); mapindex(r, n)
#'  
#' @seealso \code{\link[=NPtest_indept]{NPtest_indept}} uses this function to 
#' run the independence test.
#' 
#' @references
#' Haiyan Wang, Siti Tolos, and Suojin Wang (2010). A Distribution Free
#'  Nonparametric Test to Detect Dependence Between a Response Variable and
#'  Covariate in Presence of Heteroscedastic Treatment Effects.
#'  The Canadian Journal of Statistics. 38(3), 408433. Doi:10.1002/cjs.10068
#' 
#' @useDynLib fastPSSIM
#' 
#' @export
mapindex <- function(r, n) {
    .Call(`_fastPSSIM_mapindex`, r, n)
}

#' Get the starting and ending position in a vector
#' 
#' @description
#' Function \code{trt_position()} gives the starting and ending index of 
#' covariate values in the \eqn{i_1^{th}} group of all the covariate values 
#' from all treatment groups that are together in a vector. E.g., covariate 
#' values in group 1 start from first value to the \eqn{n_1^{th}} value; those 
#' in group 2 start from \eqn{n_1 + 1} and end at the \eqn{(n_1 + n_2)^{th}} 
#' value. This function is for retrieving the position of an observation when 
#' the covariate values from all treatments are stored together in one vector.
#' 
#' This is a rewrite of the original \code{trt_position()} function from the
#' PSSIM library using Rcpp to decrease runtime. If you load both this library 
#' and PSSIM, load this one second so the faster functions will overwrite the 
#' slower ones.
#'
#' @param i1 An integer between 1 and \code{length(n)}.
#' @param n A vector of the sample sizes.
#' 
#' @return A 2-d vector, where the first gives the lower bound of treatment
#' \code{i1} and the second gives the upper bound.
#' 
#' @examples
#' i = 2; n = c(7, 8); trt_position(i, n)
#'  
#' @seealso \code{\link[=NPtest_indept]{NPtest_indept}} uses this function to 
#' run the independence test.
#' 
#' @references
#' Haiyan Wang, Siti Tolos, and Suojin Wang (2010). A Distribution Free
#'  Nonparametric Test to Detect Dependence Between a Response Variable and
#'  Covariate in Presence of Heteroscedastic Treatment Effects.
#'  The Canadian Journal of Statistics. 38(3), 408433. Doi:10.1002/cjs.10068
#' 
#' @useDynLib fastPSSIM
#' 
#' @export
trt_position <- function(i1, n) {
    .Call(`_fastPSSIM_trt_position`, i1, n)
}

